### ISSUE TITLE
pkg 'future' pinned to exactly 0.16.0 causes error

### ISSUE THREAD

**Issue by erikpaasonen** [operatingops/terraform_external_data#10]
When including `terraform_external_data` in a `requirements.txt` file, I get the following error:
> terraform-external-data 0.0.5 has requirement future==0.16.0, but you'll have future 0.17.1 which is incompatible.

Wondering if this line can be updated to require _at least_ 0.16.0 instead of _exactly_ 0.16.0?
https://github.com/operatingops/terraform_external_data/blob/master/setup.py#L18

Near as I can tell, `terraform_external_data` seems to work fine despite the warning.

**Comment by operatingops** [comment]
@erikpaasonen yeah no problem - the latest version still passes the tests. I poked around the future docs and the API doesn't seem to be stable yet, but we only use `print_function` and that's unlikely to change anytime before Python 2 gets retired in #7 (when we'll just get rid of this dependency). I'll update and release in a minute. Thanks for the detailed issue!

**Comment by operatingops** [comment]
@erikpaasonen `0.0.6` is on PyPI now with the new deps.
