### ISSUE TITLE
Add functools.wraps or wrapt?

### ISSUE THREAD

**Issue by operatingops** [operatingops/terraform_external_data#3]
The existing decorator doesn't use [functools.wraps](https://docs.python.org/3/library/functools.html#functools.wraps) or [wrapt](https://wrapt.readthedocs.io/en/latest/). At time of writing they didn't seem needed; this decorator should only ever get used in helpers to terraform and I doubted the loss of metadata, etc. would ever matter. However, I didn't do anything to confirm and I'm not very familiar with those tools at the moment. A review of that choice is worthwhile.

**Comment by aaronchall** [comment]
My thoughts: the issue isn't important enough to warrant a new dependency, just use the standard library option.

Pull request: https://github.com/operatingops/terraform_external_data/pull/4

**Comment by operatingops** [comment]
Works for me - thanks for reviewing @aaronchall!
