### ISSUE TITLE
Remove support for Python 2

### ISSUE THREAD

**Issue by operatingops** [operatingops/terraform_external_data#7]
Python 2.7 will be [supported until 2020](https://www.python.org/dev/peps/pep-0373/#id2), but that "does not guarantee that bugfix releases will be made on a regular basis". Given that this helper is meant to be run with modern versions of a modern deployment tool, Python 2 support is likely not a significant feature. To avoid impact from bugs that don't get fixed quickly, it may be better to remove support. This will also simplify the code and the test suite. However, this is also a library and since Python 2 is still officially supported it may be a better practice to keep it until official support ends.

This is a breaking change and would have to be a major version bump.

**Comment by beddari** [comment]
My vote would be to keep it until distros switch, lots of users would most likely have Ansible somewhere close, that runs on the system Python ...

**Comment by operatingops** [comment]
@beddari so you're thinking folks would be using this to pass data from Ansible in to Terraform?
